In [1]:
# import relate packages
import numpy as np

In [77]:
np.random.seed(0)
X1 = np.random.randint(100, size = (10))
X2 = np.random.randint(100, size = (4, 4))

**Question 1: Fancy Indexing**

- a. Print X1
- b. Print the 2nd, 6th, 3rd, 8th (0-indexing) elements in X1
- c. Create a new array by X1 with index [ 2, 6, 3, 8 ]
- d. Create a new array by X1 with index [ [2, 6], [3, 8] ]

In [78]:
# a.
print(X1)


[44 47 64 67 67  9 83 21 36 87]


In [79]:
# b.
print(X1[2])
print(X1[6])
print(X1[3])
print(X1[8])

64
83
67
36


In [80]:
# c.
ind=[2, 6, 3, 8]
print(X1[ind])

[64 83 67 36]


In [81]:
# d. 
ind=np.array([[2, 6], [3, 8]])
print(X1[ind])

[[64 83]
 [67 36]]


**Question 2: Fancy Indexing**

- a. print X2
- b. print the [1,3], [2,2], [3,1] elements in X2
- c. create a new array by X2 with index [[1, 2, 3], [3, 2, 1]]
- d. create a new array that is a submatrix of X2
    - whose rows are indexed by [1, 2, 3] and
    - whose columns are indexed by [3, 2, 1]
    - Try use: [row[:, np.newaxis], col]

In [82]:
# a.
print(X2)

[[70 88 88 12]
 [58 65 39 87]
 [46 88 81 37]
 [25 77 72  9]]


In [83]:
# b.
print(X2[1, 3])
print(X2[2, 2])
print(X2[3, 1])

87
81
77


In [84]:
# c.
row=np.array([1, 2, 3])
col=np.array([3, 2, 1])
print(X2[row, col])


[87 81 77]


In [85]:
# d.
row=np.array([1, 2, 3])
col=np.array([3, 2, 1])
print(X2[row[:, np.newaxis], col])

[[87 39 65]
 [37 81 88]
 [ 9 72 77]]


**Q3: Combining fancy indexing with other indexing schemes**

- a. print X2
- b. print the 3rd (0-indexing) row of X2 as a 1-dimensional array
- c. print a 1-dimensional array
     - whose entries are the 3rd, 1st, 2nd entries of the 3rd row of X2
- d. create a new array that is a submatrix of X2
     - whose rows are indexed by [2,1] and
     - whose columns are indexed by [3,1,2]

In [22]:
# a.
print(X2)

[[70 88 88 12]
 [58 65 39 87]
 [46 88 81 37]
 [25 77 72  9]]


In [24]:
# b.
print(X2[3,:])

[25 77 72  9]


In [27]:
# c.
print(X2[3:,[3, 1, 2]])

[[ 9 77 72]]


In [30]:
# d.
row=np.array([2, 1])
col=np.array([3, 1, 2])
print(X2[row[:, np.newaxis],col])

[[37 88 81]
 [87 65 39]]


**Q4: Modifying values with fancy indexing**

In [86]:
X3 = np.arange(10)

- a. print X3
- b. change the 3rd, 6th, 8th values in X3 into 15
- c. substract 10 from the 2nd, 6th and 8th elements in X3

In [87]:
# a.
print(X3)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
# b.
X3[3]=15
X3[6]=15
X3[8]=15
print(X3)

[ 0  1  2 15  4  5 15  7 15  9]


In [89]:
# c.
X3[2]-=10
X3[6]-=10
X3[8]-=10
print(X3)

[ 0  1 -8 15  4  5  5  7  5  9]


**Q5: Sorting and argsorting of rows or columns**

- a. sort each column of X2
- b. sort each row of X2
- c. gives the order index along the columns of X2
- d. gives the order index along the rows of X2

In [90]:
X2

array([[70, 88, 88, 12],
       [58, 65, 39, 87],
       [46, 88, 81, 37],
       [25, 77, 72,  9]])

In [91]:
# a.
X5=np.sort(X2, axis=0)
X5

array([[25, 65, 39,  9],
       [46, 77, 72, 12],
       [58, 88, 81, 37],
       [70, 88, 88, 87]])

In [92]:
# b.
X6=np.sort(X2, axis=1)
X6

array([[12, 70, 88, 88],
       [39, 58, 65, 87],
       [37, 46, 81, 88],
       [ 9, 25, 72, 77]])

In [93]:
# c.
i5=np.argsort(X2, axis=0)
i5

array([[3, 1, 1, 3],
       [2, 3, 3, 0],
       [1, 0, 2, 2],
       [0, 2, 0, 1]], dtype=int64)

In [94]:
# d.
i6=np.argsort(X2)
i6

array([[3, 0, 1, 2],
       [2, 0, 1, 3],
       [3, 0, 2, 1],
       [3, 0, 2, 1]], dtype=int64)