In [1]:
import numpy as np
import pandas as pd

In [3]:
print("version", np.version.version)
print(np.array([1,2,3]))
a=np.array([1,2,3], dtype='float32')
print("float array:", a)
print(a.shape)
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

version 1.22.3
[1 2 3]
float array: [1. 2. 3.]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


## Basic of numpy arrays
- Attributes of arrays
- Indexing of arrays
- Slicing of arrays
- Reshaping of arrays
- Concatenation and splitting of arrays

In [4]:
#creating arrays from scratch
print(np.zeros(10, dtype='int'))    #single dimension array

#multi-dimension array
print(np.ones((3,5), dtype='int'))
print(np.full((3,4), 3.14))

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [5]:
#Attribution of array
#[start, stop, step]
print(np.arange(0, 20, 2))

#create an array with a linear sequence(線性序列)
print("linear sequence:\n", np.linspace(0, 2, 5)) #0~2， 分五段

#create a 3*3 array of uniformly distributed random values between 0 and 1
print("random random:\n", np.random.random((3,3)))

#create a 3*3 array of normal distribution(常態分布數組) with mean(均值) 0 and standard deviation(標準差) 1
print("random normal distribution:\n", np.random.normal(0, 1, (3,3)))

#create array of random integers between 0 to 10
print("random integers:\n", np.random.randint(0, 10, (3,3)))

#return cumulative value(累積值)
b=np.array([[1,2,3], [4,5,6]])
print("b: ", b)
print("cumulative value: ", np.cumsum(b))

#標準差
print("標準差: ", np.std(b))

[ 0  2  4  6  8 10 12 14 16 18]
linear sequence:
 [0.  0.5 1.  1.5 2. ]
random random:
 [[0.25321726 0.00410294 0.20296266]
 [0.19631588 0.93388789 0.47204318]
 [0.46635958 0.45294086 0.51749781]]
random normal distribution:
 [[-0.83773699  0.96415314 -1.07622449]
 [ 0.20453661  0.72046822 -1.51619433]
 [ 1.15681546 -1.26018883  0.22357876]]
random integers:
 [[6 4 9]
 [6 5 5]
 [4 9 5]]
b:  [[1 2 3]
 [4 5 6]]
cumulative value:  [ 1  3  6 10 15 21]
標準差:  1.707825127659933


In [6]:
np.random.seed(0)
x1=np.random.randint(10, size=6) #one dimension array
x2=np.random.randint(10, size=(3, 4)) #two-dimension array
x3=np.random.randint(10, size=(3, 4, 5)) #three-dimension array
print("x1: ", x1)
print("x2: ", x2)
print("x3: ", x3)

print("x1.ndim: ", x1.ndim) #維度
print("x2.ndim: ", x2.ndim)
print("x3.ndim: ", x3.ndim)

print("x1.shape: ", x1.shape) #element number in one dimension
print("x2.shape: ", x2.shape)
print("x3.shape: ", x3.shape)


x1:  [5 0 3 3 7 9]
x2:  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3:  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x1.ndim:  1
x2.ndim:  2
x3.ndim:  3
x1.shape:  (6,)
x2.shape:  (3, 4)
x3.shape:  (3, 4, 5)


In [8]:
print("x1.size: ", x1.size) #element number
print("x2.size: ", x2.size)
print("x3.size: ", x3.size)

print("x1.dtype: ", x1.dtype) #data type
print("x2.dtype: ", x2.dtype)
print("x3.dtype: ", x3.dtype)

print("x1.itemsize: ", x1.itemsize) #element byte
print("x2.itemsize: ", x2.itemsize)
print("x3.itemsize: ", x3.itemsize)

print("x1.nbytes: ", x1.nbytes) #all bytes
print("x2.nbytes: ", x2.nbytes)
print("x3.nbytes: ", x3.nbytes)

x1.size:  6
x2.size:  12
x3.size:  60
x1.dtype:  int32
x2.dtype:  int32
x3.dtype:  int32
x1.itemsize:  4
x2.itemsize:  4
x3.itemsize:  4
x1.nbytes:  24
x2.nbytes:  48
x3.nbytes:  240


In [28]:
#indexing of array
print(x1)   #indexing starts with zero and need by N-1
print("x1[0]: ", x1[0])
print("x1[5]: ", x1[5])
print("x1[-1]: ", x1[-1])

print("x2: ", x2)
print("x2[0, 0]: ", x2[0, 0])
print("x2[2, 1]: ", x2[2, 1])
print("x2[2, 1]: ", x2[2, -1])

#Modify the value of an array element
x2[0, 0]=12
print("after modify x2[0,0]: ", x2[0,0])
print("after modify x2: \n", x2)

print("x1.dtype: ", x1.dtype)
print("x1: ", x1)
x1[0]=3.14
print("after modify x1: ", x1)

[5 0 3 3 7 9]
x1[0]:  5
x1[5]:  9
x1[-1]:  9
x2:  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x2[0, 0]:  12
x2[2, 1]:  6
x2[2, 1]:  7
after modify x2[0,0]:  12
after modify x2: 
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x1.dtype:  int32
x1:  [5 0 3 3 7 9]
after modify x1:  [3 0 3 3 7 9]


In [35]:
#Slicing of array
x=np.arange(10)
print("x: ", x)
#x[start: step: step]
print("first five elements: ", x[:5]) #first five elements
print("elements after index 5: ", x[5:]) #elements after index 5

#Access middle subarrays
print("x[4:7]: ", x[4:7])

#Access avery other element after index 1
print("x[1::3]: ", x[1::3])

#every other element starting from index 1 and stop at 8
print("x[1:8:2]: ", x[1:8:2])

#reverse the array by using -1 in steps
print("x[::-1]: ", x[::-1])

#reverse the array from a particular index
print("x[5::-2]: ", x[5::-2])

#x2[start: stop(n-1): step]
print("x2: ", x2)
print("x2[0:2, 0:3]: ", x2[0:2, 0:3]) #x2[row, column]

#every row, every other column
print("x2[:3, ::2]: ", x2[:3, ::2])

#reversing all the row
print("x2[::-1, :]: ", x2[::-1, :])

#reversing all the columns
print("x2[:, ::-1]: ", x2[:, ::-1])

#reversing subarray demensions
print("x2[::-1, ::-1]: ", x2[::-1, ::-1])


x:  [0 1 2 3 4 5 6 7 8 9]
first five elements:  [0 1 2 3 4]
elements after index 5:  [5 6 7 8 9]
x[4:7]:  [4 5 6]
x[1::3]:  [1 4 7]
x[1:8:2]:  [1 3 5 7]
x[::-1]:  [9 8 7 6 5 4 3 2 1 0]
x[5::-2]:  [5 3 1]
x2:  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x2[0:2, 0:3]:  [[12  5  2]
 [ 7  6  8]]
x2[:3, ::2]:  [[12  2]
 [ 7  8]
 [ 1  7]]


In [42]:
#reshaping of array
grid=np.arange(1, 10).reshape(3,3)
print("grid: ", grid)
x=np.array([1,2,3])
print("x: ", x)
print("x.ndim: ", x.ndim)
x1=x.reshape(3, 1)
print("x1 after reshape: ", x1)
print("x.ndim: ", x1.ndim)
print("x1.shape:", x1.shape)

grid:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
x:  [1 2 3]
x.ndim:  1
x1 after reshape:  [[1]
 [2]
 [3]]
x.ndim:  2
(3, 1)


In [13]:
#Joining and splitting of arrays (結合和分開)
x=np.array([1,2,3])
y=np.array([3,2,1])

#concate
print("np.concatenate([x, y]): ", np.concatenate([x, y]))
z=np.array([99,99,99])

print("np.concatenate([x,y,z]: ", np.concatenate([x,y,z]))

#combining the same array
grid=np.arange(1,7).reshape(2,3)
print("grid: ", grid)
print("concatenate([grid, grid]): ", np.concatenate([grid, grid])) #by default axis=0/ rows
print("concatenate([grid, grid], axis=1): ", np.concatenate([grid, grid], axis=1)) #column wise combination
print("x: ", x)
print("vstack([x, grid]): ", np.vstack([x, grid])) #vertically stack arrays

z=np.array([[99],[99]])
print("z: ", z)
print("hstack([z, grid]): ", np.hstack([z, grid])) #horizontally stack arrays


np.concatenate([x, y]):  [1 2 3 3 2 1]
np.concatenate([x,y,z]:  [ 1  2  3  3  2  1 99 99 99]
grid:  [[1 2 3]
 [4 5 6]]
concatenate([grid, grid]):  [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
concatenate([grid, grid], axis=1):  [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
x:  [1 2 3]
vstack([x, grid]):  [[1 2 3]
 [1 2 3]
 [4 5 6]]
z:  [[99]
 [99]]
hstack([z, grid]):  [[99  1  2  3]
 [99  4  5  6]]


In [10]:
#split(分開)
x=np.array([1, 2, 3, 99, 99, 3, 2, 1])
print("x: ", x)

#在前3個elements時切一刀，在前5個elements時切一刀。如果是二維數列，則先看colume的列數切刀
#https://blog.csdn.net/weixin_36670529/article/details/115979240
print("split x: ", np.split(x, [3,5])) #result will leads to N+1 subarrays. 
grid= np.arange(16).reshape(4, 4)
print("grid: ", grid)

#vertical split
upper, lower =np.vsplit(grid, [2])
print("upper: ", upper)
print("lower: ", lower)

#horizontal split
left, right =np.hsplit(grid, [2])
print("left: ", left)
print("right: ", right)

x:  [ 1  2  3 99 99  3  2  1]
split x:  [array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]
grid:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
upper:  [[0 1 2 3]
 [4 5 6 7]]
lower:  [[ 8  9 10 11]
 [12 13 14 15]]
left:  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right:  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Numpy Arrays: Universal Function (運算)


In [12]:
x=np.arange(4)
print("x:", x)

#Addition
print("x+5= ", x+5)

#Substraction
print("x-5= ", x-5)

#Multiply
print("x*5= ", x*5)

#Division
print("x/5= ", x/5)

#Power
print("x**2=", x**2) #x的2次方

#Modulus
print("x%2=", x%2) #x除以2的餘數

#Numpy Arithmatic operation
print("np.add(x, 2): ", np.add(x, 2))

#Subtraction
print("np.subtract(x, 2)", np.subtract(x, 2))

#Negation of array
print("np.negative(x):", np.negative(x)) #加負號

#Multiply
print("np.multiply(x, 4)", np.multiply(x, 4))

#Divide
print("np.divide(x, 2): ", np.divide(x, 2)) #x除以2，答案可為小數--> /(運算符號)

#floor divide
print("np.floor_divide(x, 2): ", np.floor_divide(x, 2)) #x除以2得到的「商」，去掉餘數，答案為整數

#Modulus
print("np.mod(x, 2): ", np.mod(x, 2)) #計算餘數--> %(運算符號)。 np.mod()==np.remainder()

x=np.arange(-2, 3)
print("x=np.arange(-2, 3): ", x)

#absolute
print("np.abs(x): ", abs(x)) #絕對值
print("np.abs(x): ", np.abs(x))
print("np.absolute(x): ", np.absolute(x))

x: [0 1 2 3]
x+5=  [5 6 7 8]
x-5=  [-5 -4 -3 -2]
x*5=  [ 0  5 10 15]
x/5=  [0.  0.2 0.4 0.6]
x**2= [0 1 4 9]
x%2= [0 1 0 1]
np.add(x, 2):  [2 3 4 5]
np.subtract(x, 2) [-2 -1  0  1]
np.negative(x): [ 0 -1 -2 -3]
np.multiply(x, 4) [ 0  4  8 12]
np.divide(x, 2):  [0.  0.5 1.  1.5]
np.floor_divide(x, 2):  [0 0 1 1]
np.mod(x, 2):  [0 1 0 1]
x=np.arange(-2, 3):  [-2 -1  0  1  2]
np.abs(x):  [2 1 0 1 2]
np.abs(x):  [2 1 0 1 2]
np.absolute(x):  [2 1 0 1 2]


## Aggregation(集合): Min, Max and Other

In [14]:

L=np.random.random(100) #100 elements(0~1)
print("python sum: ", sum(L)) #python in-bult aggregation function
print("numpy sum: ", np.sum(L)) #numpy in-built aggregation function)
print("\n")

"""%timeit is an IPython magic function, which can be used to 
   time a particular piece of code (a single execution statement, or a single method)."""
"""if we want to find out whether using np.sum() is any faster than using sum()"""
"""%timeit: https://stackoverflow.com/questions/29280470/what-is-timeit-in-python"""
%timeit sum(L)
%timeit np.sum(L) #使用np in-built aggregation function 運算較快

big_array= np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)



python sum:  52.12818058833704
numpy sum:  52.12818058833702


8.63 µs ± 73.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.98 µs ± 18 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
76 ms ± 784 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.27 ms ± 12.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [15]:
#python in-built min and max
print(min(L))
print(max(L))

#numpy in-built min and max
print(np.min(L))
print(np.max(L))

#numpy aggregates short syntax
print(big_array.min(), big_array.max(), big_array.sum())


0.009356704856532616
0.9952995676778876
0.009356704856532616
0.9952995676778876
1.4057692298008462e-06 0.9999994392723005 500202.5348847683


## Multi-dimentional aggregates
- Aggregation against rows or columns

# Broadcasting

In [20]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print("a+b= ", a+b)

#Addition of scalar value
print("a+5: ", a+5)

#Broadcast single array
M=np.ones((3, 3))
print("M:", M)
print("a:", a)
print("M.shape: ", M.shape)
print("a.shape:", a.shape)
print("M+a: ", M+a) #M的每一row都會+a

a+b=  [5 7 9]
a+5:  [6 7 8]
M: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a: [1 2 3]
M.shape:  (3, 3)
a.shape: (3,)
M+a:  [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [22]:
#Broadcating of both arrays
a=np.arange(3)
b=np.arange(3)[:, np.newaxis] #給row增加維度
c=np.arange(3)[np.newaxis, :] #給column增加維度
print("a:", a)
print("b:", b)
print("c: ", c)
print("a.shape: ", a.shape)
print("b.shape: ", b.shape) 
print("c.shape: ", c.shape)
print("a+b: ", a+b)

#Broadcasting of incompatible array
M=np.ones((3, 2))
a=np.arange(3)
print("M: ", M)
print("a: ", a)
a=a[:, np.newaxis]
print("M.shape: ", M.shape)
print("a.shape: ", a.shape)
print("a: ", a)
print("M+a: ", M+a)



a: [0 1 2]
b: [[0]
 [1]
 [2]]
c:  [[0 1 2]]
a.shape:  (3,)
b.shape:  (3, 1)
c.shape:  (1, 3)
a+b:  [[0 1 2]
 [1 2 3]
 [2 3 4]]
M:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
a:  [0 1 2]
M.shape:  (3, 2)
a.shape:  (3, 1)
a:  [[0]
 [1]
 [2]]
M+a:  [[1. 1.]
 [2. 2.]
 [3. 3.]]


In [41]:
print("M.shape: ", M.shape)
print("a.shape: ", a.shape)
print("M", M)
print("a[:, np.newaxis]: ", a[:, np.newaxis])
print("a[:, np.newaxis].shape: ", a[:, np.newaxis].shape)
print("M+a[:, np.newaxis]: ", M+a[:, np.newaxis])

M.shape:  (3, 2)
a.shape:  (3,)
M [[1. 1.]
 [1. 1.]
 [1. 1.]]
a[:, np.newaxis]:  [[0]
 [1]
 [2]]
a[:, np.newaxis].shape:  (3, 1)
M+a[:, np.newaxis]:  [[1. 1.]
 [2. 2.]
 [3. 3.]]


## Comparison, Masks, and Boolen Logic

- Comparison operators
1. less than <
2. greater than >
3. less than equal <=
4. greater than equal >=
5. not equal !=
6. equal ==

In [3]:
x=np.array([1, 2, 3, 4, 5, 6])
print("x: ", x)

#Less than
print("x<3: ", x<3) 
print("np.less(x, 3): ", np.less(x, 3))

#greater than
print("x>3: ", x>3) 
print("np.greater(x, 3): ", np.greater(x, 3))

#Less than equal
print("x<=3: ", x<=3) 
print("np.less_equal(x, 3): ", np.less_equal(x, 3))

#greater than equal
print("x>=3: ", x>=3) 
print("np.greater_equal(x, 3): ", np.greater_equal(x, 3))



x:  [1 2 3 4 5 6]
x<3:  [ True  True False False False False]
np.less(x, 3):  [ True  True False False False False]
x>3:  [False False False  True  True  True]
np.greater(x, 3):  [False False False  True  True  True]
x<=3:  [ True  True  True False False False]
np.less_equal(x, 3):  [ True  True  True False False False]
x>=3:  [False False  True  True  True  True]
np.greater_equal(x, 3):  [False False  True  True  True  True]


In [42]:
#two-dimentional array
'''np.random.RandomState: 偽隨機數生成。
 是用确定性的算法计算出来的似来自[0,1]均匀分布的随机数序列。并不真正的随机，
 但具有类似于随机数的统计特征，如均匀性、独立性等。
 https://blog.csdn.net/weixin_41571493/article/details/80550076'''
rng=np.random.RandomState(0) #用rng固定隨機生成的數列就是rng，之後取值時就會是rng內的值，而不是重新一行隨機數列
x=rng.randint(10, size=(3, 4))
print("rng: ", rng)
print("x: ", x)
print("x<6: ", x<6)

print("count_nonzero(x<6): ", np.count_nonzero(x<6)) #the same: np.sum(x<6)
print("np.sum(x<6): ", np.sum(x<6))

print("np.sum(x<6, axis=1)", np.sum(x<6, axis=1)) #values in column with less than 6
print("np.sum(x<6, axis=0)", np.sum(x<6, axis=0)) #values in row with less than 6

print("x: ", x)
print("any(x>8): ", np.any(x>8))
print("any(x<0): ", np.any(x<0))
print("all(x<8, axis=1)", np.all(x<8, axis=1))




rng:  RandomState(MT19937)
x:  [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
x<6:  [[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]
count_nonzero(x<6):  8
np.sum(x<6):  8
np.sum(x<6, axis=1) [4 2 2]
np.sum(x<6, axis=0) [2 2 2 2]
x:  [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
any(x>8):  True
any(x<0):  False
all(x<8, axis=1) [ True False  True]


## Example: Seattle Rainfall

In [43]:
import pandas as pd

In [5]:
df=pd.read_csv(r"seattle-weather.csv", encoding='utf8', engine='python')
df

date  precipitation  temp_max  temp_min  wind  weather
0       2012/1/1            0.0      12.8       5.0   4.7  drizzle
1       2012/1/2           10.9      10.6       2.8   4.5     rain
2       2012/1/3            0.8      11.7       7.2   2.3     rain
3       2012/1/4           20.3      12.2       5.6   4.7     rain
4       2012/1/5            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015/12/27            8.6       4.4       1.7   2.9      fog
1457  2015/12/28            1.5       5.0       1.7   1.3      fog
1458  2015/12/29            0.0       7.2       0.6   2.6      fog
1459  2015/12/30            0.0       5.6      -1.0   3.4      sun
1460  2015/12/31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [11]:
print("precipitation:\n", df['precipitation']) #precipitation=降雨

precipitation:
 0        0.0
1       10.9
2        0.8
3       20.3
4        1.3
        ... 
1456     8.6
1457     1.5
1458     0.0
1459     0.0
1460     0.0
Name: precipitation, Length: 1461, dtype: float64


In [12]:
#Days without rain
print("Days without rain:", np.sum(df['precipitation']==0))

#Number of days with rain
print("Number of days without rain:", np.sum(df['precipitation']!=0))


Days without rain: 838
Number of days without rain: 623


## Boolen Operator
- & bitwise_and
- | biiwise_or
- ~ bitwise_not 

In [51]:
# All rainy day will less than 15mm and greater than 5mm
print("All rainy day will less than 15mm and greater than 5mm:", np.sum((df['precipitation']<15) & (df['precipitation']>0)))


All rainy day will less than 15mm and greater than 5mm: 533


## Boolen Arrays as Masks

In [22]:
print("x: ", x)
print("x<5: ", x<5)
print("x[x<5]: ", x[x<5])


x:  [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
x<5:  [[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
x[x<5]:  [0 3 3 3 2 4]


In [6]:
#Condtruct a mask on all rainy days
rain=df['precipitation']>0
rain

0       False
1        True
2        True
3        True
4        True
        ...  
1456     True
1457     True
1458    False
1459    False
1460    False
Name: precipitation, Length: 1461, dtype: bool

In [7]:
df['precipitation'][rain]

1       10.9
2        0.8
3       20.3
4        1.3
5        2.5
        ... 
1452     6.1
1453     2.5
1454     5.8
1456     8.6
1457     1.5
Name: precipitation, Length: 623, dtype: float64

In [8]:
#增加資料
df['year']=pd.DatetimeIndex(df['date']).year
#df['month']=pd.DatetimeIndex(df['date']).month
#df.drop(columns=['month']) #刪除資料:https://blog.csdn.net/qq_18351157/article/details/105785367
df

date  precipitation  temp_max  temp_min  wind  weather  year
0       2012/1/1            0.0      12.8       5.0   4.7  drizzle  2012
1       2012/1/2           10.9      10.6       2.8   4.5     rain  2012
2       2012/1/3            0.8      11.7       7.2   2.3     rain  2012
3       2012/1/4           20.3      12.2       5.6   4.7     rain  2012
4       2012/1/5            1.3       8.9       2.8   6.1     rain  2012
...          ...            ...       ...       ...   ...      ...   ...
1456  2015/12/27            8.6       4.4       1.7   2.9      fog  2015
1457  2015/12/28            1.5       5.0       1.7   1.3      fog  2015
1458  2015/12/29            0.0       7.2       0.6   2.6      fog  2015
1459  2015/12/30            0.0       5.6      -1.0   3.4      sun  2015
1460  2015/12/31            0.0       5.6      -2.1   3.5      sun  2015

[1461 rows x 7 columns]

In [9]:
df2012=df[df['year']==2012]
df2012

date  precipitation  temp_max  temp_min  wind  weather  year
0      2012/1/1            0.0      12.8       5.0   4.7  drizzle  2012
1      2012/1/2           10.9      10.6       2.8   4.5     rain  2012
2      2012/1/3            0.8      11.7       7.2   2.3     rain  2012
3      2012/1/4           20.3      12.2       5.6   4.7     rain  2012
4      2012/1/5            1.3       8.9       2.8   6.1     rain  2012
..          ...            ...       ...       ...   ...      ...   ...
361  2012/12/27            4.1       7.8       3.3   3.2     rain  2012
362  2012/12/28            0.0       8.3       3.9   1.7     rain  2012
363  2012/12/29            1.5       5.0       3.3   1.7     rain  2012
364  2012/12/30            0.0       4.4       0.0   1.8  drizzle  2012
365  2012/12/31            0.0       3.3      -1.1   2.0  drizzle  2012

[366 rows x 7 columns]

In [52]:
# Calculate no rainy days in 2013 and 2014
#1 
print("No rainy days in 2013: ", np.sum((df['year']==2013) & (df['precipitation']==0)))
print("No rainy days in 2014: ", np.sum((df['year']==2014) & (df['precipitation']==0)))

#2
print("NO rainy days in 2013: ", np.sum(df[df['year']==2013]['precipitation']==0))
print("NO rainy days in 2014: ", np.sum(df[df['year']==2014]['precipitation']==0))

No rainy days in 2013:  213
No rainy days in 2014:  215
NO rainy days in 2013:  213
NO rainy days in 2014:  215


In [10]:
#Extract precipitation data from the year 2012
rainfall = df2012['precipitation']
rainfall


0       0.0
1      10.9
2       0.8
3      20.3
4       1.3
       ... 
361     4.1
362     0.0
363     1.5
364     0.0
365     0.0
Name: precipitation, Length: 366, dtype: float64

In [11]:
#All rainy days between 15mm and 5 mm in the year 2012
np.sum((rainfall<15)&(rainfall >5))

#Construct a mask on all rainy days
rain2012=df2012['precipitation']>0
rain2012

0      False
1       True
2       True
3       True
4       True
       ...  
361     True
362    False
363     True
364    False
365    False
Name: precipitation, Length: 366, dtype: bool

In [14]:
#Calculate number of days without rain in year 2012
withoutrain2012=np.sum(df2012['precipitation']==0)
print("number of days without rain:")
withoutrain2012


number of days without rain:


189

In [15]:
#Calculate number of days with rain
withrain2012=np.sum(df2012['precipitation']!=0)
withrain2012

177

In [16]:
#calculate number of days greater than 5mm rain on year 2012
greater5=np.sum(df2012['precipitation']>5)
greater5

78

## Fancy Indexing

In [75]:
#Fancy indexing in single dimension
rand=np.random.RandomState(42)
x=rand.randint(100, size=10)
print("x:",x)
print("x[2], x[3], x[7]: ", x[2], x[3], x[7])

ind=[2, 3, 7]
print("x[ind]:\n", x[ind])

#Creating a new array using x
ind=np.array([[3, 7], [4,5]])
print("x[ind]: \n", x[ind])


x: [51 92 14 71 60 20 82 86 74 74]
x[2], x[3], x[7]:  14 71 86
x[ind]:
 [14 71 86]
x[ind]: 
 [[71 86]
 [60 20]]


## Fancy indexing in multiple dimensions

In [17]:
x=np.arange(12).reshape(3,4)
print("x:\n",x)

#Creating a new array by X with below index
row=np.array([0, 1, 2])
col=np.array([2, 1, 3])
print("row: ", row)
print("col: ", col)
print("x[row, col]: ", x[row, col]) #座標: ((0,2),(1,1),(2,3))

#Creating a new array that is a submatrix of x
print("row[:, np.newaxis]:\n", row[:, np.newaxis])
print("x[row[:, np.newaxis], col]: \n", x[row[:, np.newaxis], col])
#x[row[:, np.newaxis], col]:座標
# ((0,2),(0,1),(0,3))
# ((1,2),(1,1),(1,3))
# ((2,2),(2,1),(2,3))

x:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row:  [0 1 2]
col:  [2 1 3]
x[row, col]:  [ 2  5 11]
row[:, np.newaxis]:
 [[0]
 [1]
 [2]]
x[row[:, np.newaxis], col]: 
 [[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


## Combined Indexing

In [87]:
# Combine fancy indices and simple indices
x=np.arange(12).reshape(3,4)
print("x:\n", x, '\n')
print("x[2, [2, 0, 2]]: \n", x[2, [2, 0, 2]], '\n')
#x[2, [2, 0, 2]]:座標
# ((2,2),(2,0),(2,2))


#Combine fancy indices with slicing
print("x[1:, [2, 0, 1]]: \n", x[1:, [2, 0, 1]])
#x[1:, [2, 0, 1]]:座標
# ((1,2),(1,0),(1,1))
# ((2,2),(2,0),(2,1))


x:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

x[2, [2, 0, 2]]: 
 [10  8 10] 

x[1:, [2, 0, 1]]: 
 [[ 6  4  5]
 [10  8  9]]


In [18]:
#Combine fancy indices with mask
mask=np.array([1, 0, 1, 0], dtype=bool)
print("mask:", mask)
row=np.array([0, 1, 2])

x=np.arange(12).reshape(3,4)
print("x:\n", x, '\n')
print("x[row[:np.newaxis], mask]:\n",x[row[:, np.newaxis], mask])
#x[row[:np.newaxis], mask]:座標
# ((0,0),(1,3))
# ((1,0),(2,3))
# ((2,0),(2,3))

mask: [ True False  True False]
x:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

x[row[:np.newaxis], mask]:
 [[ 0  2]
 [ 4  6]
 [ 8 10]]


## Modify values with Fancy indexing

In [19]:
x=np.arange(10)
i=np.array([2, 1, 8, 4])
print("origine x: ", x)
print("origine i: ", i)
print("x[i]: ", x[i])
x[i]=99
print("x[i]=99: ", x)

#adding values
x[i]+=10
print("x[i]+=10: ", x)

#Substracting values
x[i]-=10
print("x[i]-=10: ", x)

x[[0, 0]]=[4, 6]
print("x[[0, 0]]=[4, 6]: ", x)


origine x:  [0 1 2 3 4 5 6 7 8 9]
origine i:  [2 1 8 4]
x[i]:  [2 1 8 4]
x[i]=99:  [ 0 99 99  3 99  5  6  7 99  9]
x[i]+=10:  [  0 109 109   3 109   5   6   7 109   9]
x[i]-=10:  [ 0 99 99  3 99  5  6  7 99  9]
x[[0, 0]]=[4, 6]:  [ 6 99 99  3 99  5  6  7 99  9]


In [20]:
x=np.zeros(10)
print("x=np.zeros(10): ", x)
i=[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
x[i]+=1
print("x[i]+=1 後的x: ", x) #不管重複位置+1多少次，最終只會+1

#Repeating the adding function
np.add.at(x, i, 1) #重複位置+1多少次，就會在那個位置+1多少次
print("np.add.at(x, i, 1) 後的x: ", x)

x=np.zeros(10):  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
x[i]+=1 後的x:  [0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
np.add.at(x, i, 1) 後的x:  [0. 2. 3. 4. 5. 0. 0. 0. 0. 0.]


## Sorting Arrays

In [23]:
x=np.array([5, 4, 32, 1])
np.sort(x) #Numpy built-in function np.sort
x.sort() #Python built-in function
print("After sort x: ", x)

#To get the indices of sorted elements
#np.argsort:
#https://numpy.org/doc/stable/reference/generated/numpy.argsort.html
#https://blog.csdn.net/maoersong/article/details/21875705
i=np.argsort(x) #将x中的元素从小到大排列，提取其对应的index(索引)，然后输出到i
print("Sorted indices: ", i)
print("Sorted elements: ", x)

#Sorting of arrays along with rows and columns
rand=np.random.RandomState(42)
x=rand.randint(0, 10, (4, 6)) #範圍0~10，取4*6個
print("random x:\n", x)

#Sort each element of column x
x=np.sort(x, axis=0)
print("Sorted x of column:\n", x)

#Sort each row of x
x=np.sort(x, axis=1)
print("Sorted x of row:\n", x)

After sort x:  [ 1  4  5 32]
Sorted indices:  [0 1 2 3]
Sorted elements:  [ 1  4  5 32]
random x:
 [[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
Sorted x of column:
 [[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
Sorted x of row:
 [[0 1 1 2 4 5]
 [2 3 4 5 5 7]
 [3 4 6 6 7 7]
 [4 6 7 7 9 9]]


## Partial Sorting: Partioning 

In [23]:
x=np.array([99, 88, 77, 66, 55, 44, 33, 22, 11])
print("original x:\n", x)

#Give smallest values to the left of the partition, and
#remaining values to right in arbitrary order
print("after moving the (x, 3):\n", np.partition(x, 3)) #部分數字小的往左邊挪
#numpy.partition(a, kth, axis=-1, kind='introselect', order=None) 
#第k个位置上的元素的值在已排序的数组中所处的位置。所有小于第k个元素的元素都被移到这个元素前面
# ，所有等于或大于这个元素的元素都被移到它后面。这两个分区中元素的顺序是未定义的。
#https://numpy.org/devdocs/reference/generated/numpy.partition.html
print("after moving the (x, (1,3)):\n", np.partition(x, (1,3))) #有疑問查看上一行網址內的網頁內容


original x:
 [99 88 77 66 55 44 33 22 11]
after moving the (x, 3):
 [22 11 33 44 55 88 66 77 99]
after moving the (x, (1,3)):
 [11 22 33 44 55 66 77 88 99]


## Two dimention array sorting

In [26]:
rand = np.random.RandomState(42)
x=rand.randint(0, 10, (4, 6))
print("original x:\n", x)

#row wise partial sorting
print("row wise partial sorting:\n", np.partition(x, 2, axis=1))

#column wise partial sorting
print("column wise partial sorting:\n", np.partition(x, 2, axis=0))



original x:
 [[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
row wise sorting:
 [[3 4 6 7 6 9]
 [2 3 4 7 6 7]
 [1 2 4 5 7 7]
 [0 1 4 5 9 5]]
column wise sorting:
 [[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]


## Structured Data

In [24]:
#Create a compound dtype by specifying them as a list(square brackets) of tuples(parenthesis)
datatype = [('name', 'U10'), ('age', 'i4'),('weight', 'f4')]
print("datatype", datatype)

#Create values by specifying them as a List(square brackets) of tuples(parenthesis)
values=[('Rex', 9, 81.0), ('Fido', 3, 27.0), ('Bob', 45, 85.5)]
print("values:", values)
F=np.array(values, dtype=datatype)
print("F:", F)
print("F['name']:", F['name'])
print("F['age']:", F['age'])
print("F['weight']:", F['weight'])
print("F[0]:", F[0])
print("F[-1]:", F[-1])
print("F[-1]['name']:", F[-1]['name'])
print("F[F['age']>30]['name']:", F[F['age']>30]['name'])





datatype [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
values: [('Rex', 9, 81.0), ('Fido', 3, 27.0), ('Bob', 45, 85.5)]
F: [('Rex',  9, 81. ) ('Fido',  3, 27. ) ('Bob', 45, 85.5)]
F['name']: ['Rex' 'Fido' 'Bob']
F['age']: [ 9  3 45]
F['weight']: [81.  27.  85.5]
F[0]: ('Rex', 9, 81.)
F[-1]: ('Bob', 45, 85.5)
F[-1]['name']: Bob
F[F['age']>30]['name']: ['Bob']


In [9]:
F['name']

array(['Rex', 'Fido', 'Bob'], dtype='<U10')

# Rocord Array

In [13]:
#np.recarray: https://numpy.org/doc/stable/reference/generated/numpy.recarray.html
#np.ndarray.view: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html
data_rec=F.view(np.recarray)

#access the data as dictionary-key
print("data_rec['age']: ",data_rec['age'])

#access the data as attrubute
print("data_rec.age: ",data_rec.age)

%timeit F['age']
%timeit data_rec['age']
%timeit data_rec.age

data_rec['age']:  [ 9  3 45]
data_rec.age:  [ 9  3 45]
108 ns ± 0.92 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.66 µs ± 35.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.67 µs ± 82.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
